#!/bin/bash

# Just call the script with the name of the project

TEMPLATES=(css js pages static)
PAGE_FOLDERS=(css js html images)
FOLDER=$1
mkdir $FOLDER

for f in ${TEMPLATES[*]}; do
    mkdir "$FOLDER"/"${f}"
done

for f in ${PAGE_FOLDERS[*]}; do
    mkdir "$FOLDER"/"${TEMPLATES[2]}"/"${f}"
done

mkdir "$FOLDER"/"${TEMPLATES[3]}"/images
mkdir "$FOLDER"/"${TEMPLATES[3]}"/packages

echo "* {}" >"$FOLDER"/"${TEMPLATES[0]}"/style.css
echo "console.log('this')" >"$FOLDER"/"${TEMPLATES[1]}"/app.js

echo "* {}" >"$FOLDER"/"${TEMPLATES[2]}"/"${PAGE_FOLDERS[0]}"/style.css
echo "console.log('this')" >"$FOLDER"/"${TEMPLATES[2]}"/"${PAGE_FOLDERS[1]}"/app.js
echo "!!!" >"$FOLDER"/"${TEMPLATES[2]}"/"${PAGE_FOLDERS[2]}"/index.html

echo "!!!" >"$FOLDER"/index.html
echo "#README" >"$FOLDER"/README.md
