#!/bin/bash
FOLDERS=(css js pages static)
PAGE_FOLDERS=(css js html images)
folder=$1
mkdir $folder

for f in ${FOLDERS[*]}; do
    mkdir "$folder"/"${f}"
done

for f in ${PAGE_FOLDERS[*]}; do
    mkdir "$folder"/"${FOLDERS[2]}"/"${f}"
done

mkdir "$folder"/"${FOLDERS[3]}"/images
mkdir "$folder"/"${FOLDERS[3]}"/packages

echo "* {}" >"$folder"/"${FOLDERS[0]}"/style.css
echo "console.log('this')" >"$folder"/"${FOLDERS[1]}"/app.js

echo "* {}" >"$folder"/"${FOLDERS[2]}"/"${PAGE_FOLDERS[0]}"/style.css
echo "console.log('this')" >"$folder"/"${FOLDERS[2]}"/"${PAGE_FOLDERS[1]}"/app.js
echo "!!!" >"$folder"/"${FOLDERS[2]}"/"${PAGE_FOLDERS[2]}"/index.html

echo "!!!" >"$folder"/index.html
echo "#README" >"$folder"/README.md
