#!/bin/bash

# Just call the script with the name of the project

TEMPLATES=(Templates Css Js Static)
FOLDER=$1
mkdir $FOLDER

for f in ${TEMPLATES[*]}; do
    mkdir "$FOLDER"/"${f}"
done

mkdir "$FOLDER"/"${TEMPLATES[3]}"/Images
mkdir "$FOLDER"/"${TEMPLATES[3]}"/Packages

echo "!!!" >"$FOLDER"/"${TEMPLATES[0]}"/index.html
echo "* {}" >"$FOLDER"/"${TEMPLATES[1]}"/style.css
echo "console.log('this')" >"$FOLDER"/"${TEMPLATES[2]}"/app.js
